DoistRuleSet:
  NoBlankNewLineAfterClassHeader:
    active: true
  ConsistentWhenEntries:
    active: true
  SingleLineWhenEntryExpressionsAreWrapped:
    active: true
  MutableObservablePropertyIsPrivate:
    active: true
  NoNotNullOperator:
    active: true
